name: Deploy Pokedex to VPS

on:
  push:
    branches:
      - main  # Le déploiement se lancera à chaque push sur main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 4025
          timeout: 60s
          script: |
            mkdir -p ~/apps/pokedex
            cd ~/apps/pokedex
            # Si le dossier n'est pas un dépôt git, on clone, sinon on pull
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }}.git .
            else
              git pull origin main
            fi
            docker build -t pokedex-web .
            docker stop pokedex-app || true
            docker rm pokedex-app || true
            docker run -d --name pokedex-app -p 80:80 pokedex-web